name: Testing code before merge

on:
  pull_request:
    branches: [master, develop]

jobs:
  test_on_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
